# generated by cabal-rpm-0.12.5
# https://fedoraproject.org/wiki/Packaging:Haskell

%global pkg_name purebred
%global pkgver %{pkg_name}-%{version}

%bcond_with tests

Name:           %{pkg_name}
Version:        0.1.0.0
Release:        0.20181201%{?dist}
Summary:        An mail user agent built around notmuch

License:        AGPLv3
Url:            https://github.com/romanofski/%{name}
Source0:        https://github.com/romanofski/%{name}/archive/%{version}.tar.gz

BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-rpm-macros
# Begin cabal-rpm deps:
BuildRequires:  chrpath
BuildRequires:  ghc-attoparsec-devel
BuildRequires:  ghc-brick-devel
BuildRequires:  ghc-bytestring-devel
BuildRequires:  ghc-case-insensitive-devel
BuildRequires:  ghc-containers-devel
BuildRequires:  ghc-deepseq-devel
BuildRequires:  ghc-directory-devel
BuildRequires:  ghc-dyre-devel
BuildRequires:  ghc-exceptions-devel
BuildRequires:  ghc-filepath-devel
BuildRequires:  ghc-lens-devel
BuildRequires:  ghc-mime-types-devel
BuildRequires:  ghc-mtl-devel
BuildRequires:  ghc-notmuch-devel
BuildRequires:  ghc-optparse-applicative-devel
BuildRequires:  ghc-purebred-email-devel
BuildRequires:  ghc-random-devel
BuildRequires:  ghc-text-devel
BuildRequires:  ghc-text-zipper-devel
BuildRequires:  ghc-time-devel
BuildRequires:  ghc-typed-process-devel
BuildRequires:  ghc-vector-devel
BuildRequires:  ghc-vty-devel
%if %{with tests}
BuildRequires:  ghc-quickcheck-instances-devel
BuildRequires:  ghc-regex-posix-devel
BuildRequires:  ghc-stm-devel
BuildRequires:  ghc-tasty-devel
BuildRequires:  ghc-tasty-hunit-devel
BuildRequires:  ghc-tasty-quickcheck-devel
BuildRequires:  ghc-temporary-devel
BuildRequires:  ghc-unix-devel
%endif
# End cabal-rpm deps
# Start cabal hack to get support for Cabal 2.4
BuildRequires:  cabal-install > 1.18
# end cabal hack

%description
An MUA built around <https://notmuchmail.org/ notmuch>. Mutt-inspired console
interface, but embracing the notmuch storage / search paradigm.

= Requirements

* GHC >= 8.2
* notmuch
* a local mailer (e.g. 'sendmail')

= Status

The project is in development and is not ready for serious use.
Contributions are welcome (bug reports, feedback, doc, code, etc). See HACKING
for more info.


%package -n ghc-%{name}
Summary:        Haskell %{name} library

%description -n ghc-%{name}
This package provides the Haskell %{name} shared library.


%package -n ghc-%{name}-devel
Summary:        Haskell %{name} library development files
Provides:       ghc-%{name}-static = %{version}-%{release}
Provides:       ghc-%{name}-doc = %{version}-%{release}
%if %{defined ghc_version}
Requires:       ghc-compiler = %{ghc_version}
Requires(post): ghc-compiler = %{ghc_version}
Requires(postun): ghc-compiler = %{ghc_version}
%endif
Requires:       ghc-%{name}%{?_isa} = %{version}-%{release}

%description -n ghc-%{name}-devel
This package provides the Haskell %{name} library development files.


%prep
%setup -q


%build
# start cabal hack to get Cabal 2.4 support
%global cabal cabal
%cabal update
%cabal sandbox init
%cabal install --only-dependencies
# end cabal hack
%ghc_lib_build


%install
%ghc_lib_install
%ghc_fix_rpath %{pkgver}
mv %{buildroot}%{_ghclicensedir}/{,ghc-}%{name}


%check
%cabal_test


%post -n ghc-%{name}-devel
%ghc_pkg_recache


%postun -n ghc-%{name}-devel
%ghc_pkg_recache


%files
%doc README.md
%{_bindir}/%{name}


%files -n ghc-%{name} -f ghc-%{name}.files
%license LICENSE


%files -n ghc-%{name}-devel -f ghc-%{name}-devel.files
%doc README.md


%changelog
* Mon Feb 18 2018 Róman Joost <roman@bromeco.de> - 0.1.0.0-0.20181201
- new nightly build

* Sat Dec  1 2018 Fedora Haskell SIG <haskell@lists.fedoraproject.org> - 0.1.0.0-1
- spec file generated by cabal-rpm-0.12.5
