name: Haskell Lint
on:
  - push
  - pull_request
jobs:
  linux:
    name: HLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: apt
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends gnupg ca-certificates dirmngr curl

      - name: hlint
        run: |
          curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .
