name: NixOS Build (Flakes - build only)
on:
  - push
  - pull_request
jobs:
  linux:
    name: Nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Local cache
        uses: actions/cache@v2
        with:
          path: /nix/store
          key: "{{ runner.os }}-Nixpkgs-integration-test"

      - name: verify nix package manager installation script
        run: |
          curl -o install-nix-2.9.1 https://releases.nixos.org/nix/nix-2.9.1/install
          curl -o install-nix-2.9.1.asc https://releases.nixos.org/nix/nix-2.9.1/install.asc
          gpg2 --keyserver hkps://keyserver.ubuntu.com --recv-keys B541D55301270E0BCF15CA5D8170B4726D7198DE
          gpg2 --verify ./install-nix-2.9.1.asc

      - run: sh ./install-nix-2.9.1 --no-daemon

      - name: Enable Nix Flakes
        run: |
          . ~/.nix-profile/etc/profile.d/nix.sh
          nix-env -iA nixpkgs.nixFlakes
          mkdir -p ~/.config/nix
          echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf

      - name: Set paths
        run: |
          echo "/nix/var/nix/profiles/default/bin" >> "$GITHUB_PATH"
          echo "/nix/var/nix/profiles/per-user/$USER/profile/bin" >> "$GITHUB_PATH"
          if [[ $INPUT_NIX_PATH != "" ]]; then
            echo "NIX_PATH=${INPUT_NIX_PATH}" >> "$GITHUB_ENV"
          fi

      - run: |
          nix flake check

      - run: |
          nix build

      - run: |
          nix develop

