name: NixOS Build
on:
  - push
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    name: Nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
            extra-substituters = https://cache.iog.io
            extra-trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=

      - name: Build (default.nix)
        run: nix-build -j auto

      - name: Man pages
        run: |
          printf '[database]\npath=%s\n' "$PWD" > "$HOME/.notmuch-config"
          nix-shell --run 'PATH="$PWD/result/bin:$PATH" make -C docs/man'
