name: NixOS Build
on:
  - push
  - pull_request
jobs:
  linux:
    name: Nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Local cache
        uses: actions/cache@v2
        with:
          path: /nix/store
          key: "{{ runner.os }}-Nixpkgs-integration-test"

      - name: Install Nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: "nixpkgs=channel:nixos-unstable"

      - name: Install system dependencies
        run: |
          nix-env --install elinks -f '<nixpkgs>'

      - name: Build
        shell: bash
        run: |
          nix-build -j auto
          nix-shell --command 'PATH=$PATH:result/bin cabal v2-test --test-show-details=streaming uat'
          echo -e "[database]\npath=$(pwd)" > ${HOME}/.notmuch-config
          nix-shell --command 'pushd docs/man && PATH=$PATH:../../result/bin make && popd'
