name: NixOS Build (Flakes - build only)
on:
  - push
  - pull_request
jobs:
  linux:
    name: Nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - run: |
          nix flake check

      - run: |
          nix build

      - run: |
          nix print-dev-env .#shell-with-icu

      - run: |
          nix develop .#purebred -c bash -c "echo $PATH"
          nix develop -c bash -c "PATH=result/bin:$PATH cabal v2-test --test-show-details=streaming uat"
        name: Run UAT

      - run: |
          echo -e "[database]\npath=$(pwd)" > ${HOME}/.notmuch-config
          nix develop -c bash -c "pushd docs/man && PATH=$PATH:../../result/bin make && popd"
        name: Build documentation

